<?php
// 1.) Fill in all the empty fields with their appropriate settings inbetween ''.
// 2.) Rename this file to config.inc

  //Server name (like 'localhost' if the server is localhost).
  $server = '';
  //Database name.
  $dbname = '';
  //Username (database user with basic read-write acces)
  $user = '';
  //Password of the Database-user
  $pass = '';
  //SMTP setup for overriding php.ini smtp-setting
  $smtp = '';
  //Only activate if needed.
  //Activate by removing #
  #ini_set('SMTP', "$smtp");
  //Root url off the website
  $websiteurl = '';
?>
